### ISSUE TITLE
Line 99 and 356 uses template strings

### ISSUE THREAD

**Issue by tunnckoCore** [node-base/base-runner#3]
As we comment in some commit comments.

https://github.com/node-base/base-runner/blob/master/index.js#L99
https://github.com/node-base/base-runner/blob/master/index.js#L356

Just to don't forget it. I may send PR this weekend.

**Comment by jonschlinkert** [comment]
:+1: thanks a lot for this. will help me remember

**Comment by jonschlinkert** [comment]
I have a lot of updates to push up for base-generators, so don't waste time on that one. if you have issues with generators resolving, hopefully those will be fixed by end of the weekend

**Comment by tunnckoCore** [comment]
Haha, ookey, so I'll rest this weekend and wait. LOL. :+1:

**Comment by jonschlinkert** [comment]
I'm going to keep these in. We haven't had any issues created so far with 2k downloads or so. not that 2k is a lot of downloads, but if it was a major problem we would have heard about it by now. I'm still of the opinion that we should be supporting the move towards new versions of node.js. 

we'll update the engines property in package.json to reflect this.
